import requests
dados = requests.get ("https://previsao-de-resultados-default-rtdb.firebaseio.com/.json")
dados = dados.json()
print (dados)
time1 = str(input("Qual é o 1° time: "))
def primeiro_time():
    if time1 == "ame-mg" or time1 == "america mineiro" or time1 == "ame-mineiro" or time1 == "américa mineiro" or time1 == "américa-mg" or time1 == "america-mg" or time1 == "america-mineiro":
        print ("AMÉRICA-MG")
        print ("JOGOS: ", dados['ame']['jogos'])
        print ("GOLS FEITOS: ", dados['ame']['gols_feitos'])
        print ("GOLS SOFRIDOS: ", dados['ame']['gols_sofridos'])
        golf_por_jogo_time1 = (dados['ame']['gols_feitos'])/(dados['ame']['jogos'])
        print ("GOLS FEITOS POR JOGO: {:.2f}".format(golf_por_jogo_time1))
        gols_por_jogo_time1 = (dados['ame']['gols_sofridos'])/(dados['ame']['jogos'])
        print ("GOLS SOFRIDOS POR JOGO: {:.2f}".format(gols_por_jogo_time1))
    elif time1 == "atl-mg" or time1 == "atletico mineiro" or time1 == "atl-mineiro" or time1 == "atlético mineiro" or time1 == "atlético-mg" or time1 == "atletico-mg" or time1 == "atletico-mineiro":
        print ("ATLÉTICO-MG")
        print ("JOGOS: ", dados['atl-mg']['jogos'])
        print ("GOLS FEITOS: ", dados['atl-mg']['gols_feitos'])
        print ("GOLS SOFRIDOS: ", dados['atl-mg']['gols_sofridos'])
        golf_por_jogo_time1 = (dados['atl-mg']['gols_feitos'])/(dados['atl-mg']['jogos'])
        print ("GOLS FEITOS POR JOGO: {:.2f}".format(golf_por_jogo_time1))
        gols_por_jogo_time1 = (dados['atl-mg']['gols_sofridos'])/(dados['atl-mg']['jogos'])
        print ("GOLS SOFRIDOS POR JOGO: {:.2f}".format(gols_por_jogo_time1))
    elif time1 == "atl-go" or time1 == "atletico goianiense" or time1 == "atl-goianiense" or time1 == "atlético goianiense" or time1 == "atlético-go" or time1 == "atletico-go" or time1 == "atletico-go":
        print ("ATLÉTICO-GO")
        print ("JOGOS: ", dados['atl-go']['jogos'])
        print ("GOLS FEITOS: ", dados['atl-go']['gols_feitos'])
        print ("GOLS SOFRIDOS: ", dados['atl-go']['gols_sofridos'])
        golf_por_jogo_time1 = (dados['atl-go']['gols_feitos'])/(dados['atl-go']['jogos'])
        print ("GOLS FEITOS POR JOGO: {:.2f}".format(golf_por_jogo_time1))
        gols_por_jogo_time1 = (dados['atl-go']['gols_sofridos'])/(dados['atl-go']['jogos'])
        print ("GOLS SOFRIDOS POR JOGO: {:.2f}".format(gols_por_jogo_time1))
    elif time1 == "atl-pr" or time1 == "atletico paranaense" or time1 == "atl-paranaense" or time1 == "atlético paranaense" or time1 == "atlético-pr" or time1 == "atletico-pr" or time1 == "atletico-pr":
        print ("ATLÉTICO-PR")
        print ("JOGOS: ", dados['atl-pr']['jogos'])
        print ("GOLS FEITOS: ", dados['atl-pr']['gols_feitos'])
        print ("GOLS SOFRIDOS: ", dados['atl-pr']['gols_sofridos'])
        golf_por_jogo_time1 = (dados['atl-pr']['gols_feitos'])/(dados['atl-pr']['jogos'])
        print ("GOLS FEITOS POR JOGO: {:.2f}".format(golf_por_jogo_time1))
        gols_por_jogo_time1 = (dados['atl-pr']['gols_sofridos'])/(dados['atl-pr']['jogos'])
        print ("GOLS SOFRIDOS POR JOGO: {:.2f}".format(gols_por_jogo_time1))
    elif time1 == "bah" or time1 == "BAH" or time1 == "Bahia" or time1 == "bahia" or time1 == "BAHIA":
        print ("BAHIA")
        print ("JOGOS: ", dados['bah']['jogos'])
        print ("GOLS FEITOS: ", dados['bah']['gols_feitos'])
        print ("GOLS SOFRIDOS: ", dados['bah']['gols_sofridos'])
        golf_por_jogo_time1 = (dados['bah']['gols_feitos'])/(dados['bah']['jogos'])
        print ("GOLS FEITOS POR JOGO: {:.2f}".format(golf_por_jogo_time1))
        gols_por_jogo_time1 = (dados['bah']['gols_sofridos'])/(dados['bah']['jogos'])
        print ("GOLS SOFRIDOS POR JOGO: {:.2f}".format(gols_por_jogo_time1))
    elif time1 == "bgt" or time1 == "BGT" or time1 == "Bragantino" or time1 == "bragantino" or time1 == "BRAGANTINO":
        print ("BRAGANTINO")
        print ("JOGOS: ", dados['bgt']['jogos'])
        print ("GOLS FEITOS: ", dados['bgt']['gols_feitos'])
        print ("GOLS SOFRIDOS: ", dados['bgt']['gols_sofridos'])
        golf_por_jogo_time1 = (dados['bgt']['gols_feitos'])/(dados['bgt']['jogos'])
        print ("GOLS FEITOS POR JOGO: {:.2f}".format(golf_por_jogo_time1))
        gols_por_jogo_time1 = (dados['bgt']['gols_sofridos'])/(dados['bgt']['jogos'])
        print ("GOLS SOFRIDOS POR JOGO: {:.2f}".format(gols_por_jogo_time1))
    elif time1 == "cea" or time1 == "CEA" or time1 == "ceara" or time1 == "ceará" or time1 == "Ceara" or time1 == "Ceará" or time1 == "CEARA" or time1 == "CEARÁ":
        print ("CEARÁ")
        print ("JOGOS: ", dados['cea']['jogos'])
        print ("GOLS FEITOS: ", dados['cea']['gols_feitos'])
        print ("GOLS SOFRIDOS: ", dados['cea']['gols_sofridos'])
        golf_por_jogo_time1 = (dados['cea']['gols_feitos'])/(dados['cea']['jogos'])
        print ("GOLS FEITOS POR JOGO: {:.2f}".format(golf_por_jogo_time1))
        gols_por_jogo_time1 = (dados['cea']['gols_sofridos'])/(dados['cea']['jogos'])
        print ("GOLS SOFRIDOS POR JOGO: {:.2f}".format(gols_por_jogo_time1))
    elif time1 == "cor" or time1 == "COR" or time1 == "corinthians" or time1 == "Corinthians" or time1 == "CORINTHIANS":
        print ("CORINTHIANS")
        print ("JOGOS: ", dados['cor']['jogos'])
        print ("GOLS FEITOS: ", dados['cor']['gols_feitos'])
        print ("GOLS SOFRIDOS: ", dados['cor']['gols_sofridos'])
        golf_por_jogo_time1 = (dados['cor']['gols_feitos'])/(dados['cor']['jogos'])
        print ("GOLS FEITOS POR JOGO: {:.2f}".format(golf_por_jogo_time1))
        gols_por_jogo_time1 = (dados['cor']['gols_sofridos'])/(dados['cor']['jogos'])
        print ("GOLS SOFRIDOS POR JOGO: {:.2f}".format(gols_por_jogo_time1))
    elif time1 == "cui" or time1 == "CUI"or time1 == "cuiaba" or time1 == "cuiabá" or time1 == "Cuiaba" or time1 == "Cuiabá" or time1 == "CUIABA" or time1 == "CUIABÁ":
        print ("CUIABÁ")
        print ("JOGOS: ", dados['cui']['jogos'])
        print ("GOLS FEITOS: ", dados['cui']['gols_feitos'])
        print ("GOLS SOFRIDOS: ", dados['cui']['gols_sofridos'])
        golf_por_jogo_time1 = (dados['cui']['gols_feitos'])/(dados['cui']['jogos'])
        print ("GOLS FEITOS POR JOGO: {:.2f}".format(golf_por_jogo_time1))
        gols_por_jogo_time1 = (dados['cui']['gols_sofridos'])/(dados['cui']['jogos'])
        print ("GOLS SOFRIDOS POR JOGO: {:.2f}".format(gols_por_jogo_time1))
    elif time1 == "fla" or time1 == "FLA" or time1 == "flamengo" or time1 == "Flamengo" or time1 == "FLAMENGO":
        print ("FLAMENGO")
        print ("JOGOS: ", dados['fla']['jogos'])
        print ("GOLS FEITOS: ", dados['fla']['gols_feitos'])
        print ("GOLS SOFRIDOS: ", dados['fla']['gols_sofridos'])
        golf_por_jogo_time1 = (dados['fla']['gols_feitos'])/(dados['fla']['jogos'])
        print ("GOLS FEITOS POR JOGO: {:.2f}".format(golf_por_jogo_time1))
        gols_por_jogo_time1 = (dados['fla']['gols_sofridos'])/(dados['fla']['jogos'])
        print ("GOLS SOFRIDOS POR JOGO: {:.2f}".format(gols_por_jogo_time1))
    elif time1 == "flu" or time1 == "FLU" or time1 == "fluminense" or time1 == "Fluminense" or time1 == "FLUMINENSE":
        print ("FLUMINENSE")
        print ("JOGOS: ", dados['flu']['jogos'])
        print ("GOLS FEITOS: ", dados['flu']['gols_feitos'])
        print ("GOLS SOFRIDOS: ", dados['flu']['gols_sofridos'])
        golf_por_jogo_time1 = (dados['flu']['gols_feitos'])/(dados['flu']['jogos'])
        print ("GOLS FEITOS POR JOGO: {:.2f}".format(golf_por_jogo_time1))
        gols_por_jogo_time1 = (dados['flu']['gols_sofridos'])/(dados['flu']['jogos'])
        print ("GOLS SOFRIDOS POR JOGO: {:.2f}".format(gols_por_jogo_time1))
    elif time1 == "for" or time1 == "FOR" or time1 == "fortaleza" or time1 == "Fortaleza" or time1 == "FORTALEZA":
        print ("FORTALEZA")
        print ("JOGOS: ", dados['for']['jogos'])
        print ("GOLS FEITOS: ", dados['for']['gols_feitos'])
        print ("GOLS SOFRIDOS: ", dados['for']['gols_sofridos'])
        golf_por_jogo_time1 = (dados['for']['gols_feitos'])/(dados['for']['jogos'])
        print ("GOLS FEITOS POR JOGO: {:.2f}".format(golf_por_jogo_time1))
        gols_por_jogo_time1 = (dados['for']['gols_sofridos'])/(dados['for']['jogos'])
        print ("GOLS SOFRIDOS POR JOGO: {:.2f}".format(gols_por_jogo_time1))
    elif time1 == "gre" or time1 == "gre" or time1 == "gremio" or time1 == "grêmio" or time1 == "Gremio" or time1 == "GREMIO" or time1 == "Grêmio" or time1 == "GRÊMIO":
        print ("GRÊMIO")
        print ("JOGOS: ", dados['gre']['jogos'])
        print ("GOLS FEITOS: ", dados['gre']['gols_feitos'])
        print ("GOLS SOFRIDOS: ", dados['gre']['gols_sofridos'])
        golf_por_jogo_time1 = (dados['gre']['gols_feitos'])/(dados['gre']['jogos'])
        print ("GOLS FEITOS POR JOGO: {:.2f}".format(golf_por_jogo_time1))
        gols_por_jogo_time1 = (dados['gre']['gols_sofridos'])/(dados['gre']['jogos'])
        print ("GOLS SOFRIDOS POR JOGO: {:.2f}".format(gols_por_jogo_time1))
    elif time1 == "int" or time1 == "internacional" or time1 == "INT" or time1 == "Internacional" or time1 == "INTERNACIONAL":
        print ("INTERNACIONAL")
        print ("JOGOS: ", dados['int']['jogos'])
        print ("GOLS FEITOS: ", dados['int']['gols_feitos'])
        print ("GOLS SOFRIDOS: ", dados['int']['gols_sofridos'])
        golf_por_jogo_time1 = (dados['int']['gols_feitos'])/(dados['int']['jogos'])
        print ("GOLS FEITOS POR JOGO: {:.2f}".format(golf_por_jogo_time1))
        gols_por_jogo_time1 = (dados['int']['gols_sofridos'])/(dados['int']['jogos'])
        print ("GOLS SOFRIDOS POR JOGO: {:.2f}".format(gols_por_jogo_time1))
    elif time1 == "juv" or time1 == "juventude" or time1 == "JUV" or time1 == "Juventude" or time1 == "JUVENTUDE":
        print ("JUVENTUDE")
        print ("JOGOS: ", dados['juv']['jogos'])
        print ("GOLS FEITOS: ", dados['juv']['gols_feitos'])
        print ("GOLS SOFRIDOS: ", dados['juv']['gols_sofridos'])
        golf_por_jogo_time1 = (dados['juv']['gols_feitos'])/(dados['juv']['jogos'])
        print ("GOLS FEITOS POR JOGO: {:.2f}".format(golf_por_jogo_time1))
        gols_por_jogo_time1 = (dados['juv']['gols_sofridos'])/(dados['juv']['jogos'])
        print ("GOLS SOFRIDOS POR JOGO: {:.2f}".format(gols_por_jogo_time1))
primeiro_time()
